server:
  port: 9090
spring:
  application:
    name: gateway-test
  cloud:
    gateway:
      routes:
        - id: scheduling-route
          uri: http://localhost:3000
          predicates:
            - Path=/scheduling/**
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"